slurm_job_number: 
block_size: "4M"
directory: /mnt/cephtest-fi5/test-rep3-ssd/skrit/fio 
time: 130 
io_type: write
platform_type: Fi5-rep3-ssd-fuse
split_hosts_file: 0
job_number: '16,8,4,2'
node_count: 24,16,8,4,2
hosts_file:
no_scrub: 0
unit_restart: 1
job_note: "Testing FIO for comparison, trying to find out if excluding 4K runs in between 4M runs somehow effects performance of 4M. Plot Title: Fi5 Pacific comparison, only 4M (excluding 4K) SSD,rep3,fuse,"
template_path: /mnt/home/skrit/Documents/testing_clones/clone1/PyBenchFramework/examples/template/template.fio
file_size: "40G"
wait_for_others: 1
