slurm_job_number: 
block_size: 4k
directory: /mnt/cephtest/test-ec63/skrit/fio-test/tmp  
time: 300
io_type: write
platform_type: EC63 
split_hosts_file: 1
job_number: 15,10,5,1
node_count: 1
hosts-file:
no-scrub: 1
