slurm_job_number: 
block_size: "4M,64K,4K"
directory: /mnt/cephtest-fi5k/test-ec63-hdd/skrit/fio 
time: 120
io_type: write
platform_type: nvme_ec63_kernel_hdd
split_hosts_file: 0
job_number: '48,16,8,4,2,1'
node_count: 20,16,8,4,2,1
hosts_file:
no_scrub: 0
unit_restart: 1
job_note: "This test is for hdd ec63 partition after swapping bad SAS (6GB/s) cables with 12GB/s cables"
template_path: /mnt/home/skrit/Documents/testing_clones/clone1/PyBenchFramework/examples/template/template.fio
