slurm_job_number: 
block_size: "4M,64K,4K"
directory: /mnt/cephtest-fi5k/test-ec63-ssd/skrit/fio
time: 120
io_type: write
platform_type: nvme_ec63_kernel
split_hosts_file: 0
job_number: '48,16,8,4,2,1'
node_count: 20,16,8,4,2,1
hosts_file:
no_scrub: 0
unit_restart: 1
job_note: "This test is for ec63 partition after we change the number of OSDs back from 1 OSD per SSD to 2 OSDs per SSD"
template_path: /mnt/home/skrit/Documents/testing_clones/clone1/PyBenchFramework/examples/template/template.fio
