slurm_job_number: 
block_size: "4M,4K"
directory: /mnt/cephtest-fi5k/test-rep3-hdd/skrit/fio
time: 90
io_type: write
platform_type: hdd_rep3_kernel
split_hosts_file: 0
job_number: '48,16,8,4,2'
node_count: 24,16,8,4,2
hosts_file:
no_scrub: 0
unit_restart: 1
job_note: "Testing for comparison to Andras' data after system upgrade to Pacific. Plot Title: Fi5 Kernel Pacific triple rep HDD"
template_path: /mnt/home/skrit/Documents/testing_clones/clone1/PyBenchFramework/examples/template/template.fio
file_size: "40G"
wait_for_others: 1
