slurm_job_number: 
block_size: "4M,64K,4K"
directory: /mnt/cephtest-fi5/test-ec63-ssd/skrit/fio
time: 120 
io_type: write
platform_type: EC63 
split_hosts_file: 0
job_number: '48,16,8,4,2,1'
node_count: 20,16,8,4,2,1
hosts_file:
no_scrub: 0
template_path: /mnt/home/skrit/Documents/testing_clones/clone1/PyBenchFramework/examples/template/template.fio
