slurm_job_number: 
block_size: "4M,4K"
directory: /mnt/cephtest-fi5/test-ec63-ssd/skrit/fio
time: 90 
io_type: write
platform_type: nvme_ec63_fuse
split_hosts_file: 0
job_number: '48,16,8,1'
node_count: 20,16,8,1
hosts_file:
no_scrub: 0
unit_restart: 1
template_path: /mnt/home/skrit/Documents/testing_clones/clone1/PyBenchFramework/examples/template/template.fio
